POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "john123",
  "email": "john@example.com",
  "password": "mypassword"
}



### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "mypassword"
}


### FETCH QUESTIONS
GET http://localhost:5000/api/exam/questions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4OTBhZmIxNjIzYTU2ZGU4ZWVmOCIsImlhdCI6MTc1NzA5MjUzOCwiZXhwIjoxNzU3MDk2MTM4fQ.dNUocNAWeUM_PqSWlFnD-mH_KP8I1teiI9bzyPDl7po

### SUBMIT EXAM
POST http://localhost:5000/api/exam/submit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4OTBhZmIxNjIzYTU2ZGU4ZWVmOCIsImlhdCI6MTc1NzA5MjUzOCwiZXhwIjoxNzU3MDk2MTM4fQ.dNUocNAWeUM_PqSWlFnD-mH_KP8I1teiI9bzyPDl7po
Content-Type: application/json

{
  "answers": [
    { "questionId": "68baae065623e7579573518b", "selectedOption": 2 },  
    { "questionId": "68baae065623e7579573518a", "selectedOption": 1 },  
    { "questionId": "68baae065623e75795735189", "selectedOption": 3 }  
  ]
}




### FETCH RESULT
GET http://localhost:5000/api/exam/result/68bb1ad6887b80f9b86b6a7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4OTBhZmIxNjIzYTU2ZGU4ZWVmOCIsImlhdCI6MTc1NzA5MjUzOCwiZXhwIjoxNzU3MDk2MTM4fQ.dNUocNAWeUM_PqSWlFnD-mH_KP8I1teiI9bzyPDl7po